print('Hello World')
name= input('What is your name? ')
print('Hello')
print(name)
sent=input('Enter a string ')
print('These are variations:')
print('Only first letter capatalized')
print(sent.capitalize())
print('Everything in ALL CAPS')
print(sent.upper())
print('Everthing in lowercase')
print(sent.lower())
print('Counting the letter E')
print(sent.count('e'))
f_name=input('Input first name')
s_name=input('Input Last name')
print(f_name.capitalize() + s_name.capitalize())